"""Rebuild the four title outlines with fontTools (development tool only).

Input: Adobe SourceHanSerifCN-Regular.otf from the release/SubsetOTF/CN folder.
Run: python tools/title-outline.py /path/to/SourceHanSerifCN-Regular.otf
The original font is not shipped; its license is in assets/title-font.LICENSE.txt.
"""
import hashlib
import json
import sys
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.pens.recordingPen import DecomposingRecordingPen
from fontTools.pens.boundsPen import BoundsPen

font_path = Path(sys.argv[1])
expected = '3754ea669c530e2473354f8f6d9f79680a44d7e26ec7d00eeabee4a7e0753c5d'
assert hashlib.sha256(font_path.read_bytes()).hexdigest() == expected, 'Unexpected source font version'
font = TTFont(font_path)
glyphs, cmap = font.getGlyphSet(), font.getBestCmap()
paths, bounds = [], []
commands = {'moveTo': ('M', 1), 'lineTo': ('L', 1), 'curveTo': ('C', 3), 'closePath': ('Z', 0)}
for character in '风笺回廊':
    glyph = glyphs[cmap[ord(character)]]
    recording = DecomposingRecordingPen(glyphs)
    glyph.draw(recording)
    bound = BoundsPen(glyphs)
    glyph.draw(bound)
    bounds.append(bound.bounds)
    path = []
    for operation, points in recording.value:
        command, count = commands[operation]
        assert len(points) == count, 'Unsupported curve'
        path.append(command + ','.join(str(round(coordinate)) for point in points for coordinate in point))
    paths.append(''.join(path))

data = {
    'em': font['head'].unitsPerEm,
    'centerY': round((min(bound[1] for bound in bounds) + max(bound[3] for bound in bounds)) / 2),
    'paths': paths,
}
header = """'use strict';
// Generated by tools/title-outline.py. Four fixed title glyphs; not a system font.
// Outline data derived from Adobe Source Han Serif CN Regular, SIL OFL 1.1.
// Copyright 2017-2022 Adobe. See assets/title-font.LICENSE.txt.
// Source: github.com/adobe-fonts/source-han-serif, release/SubsetOTF/CN.
"""
target = Path(__file__).resolve().parents[1] / 'src' / 'title-glyphs.js'
target.write_text(header + 'module.exports = ' + json.dumps(data, separators=(',', ':')) + ';\n', encoding='utf-8')
print(f'{target.name}: {target.stat().st_size} bytes; em={data["em"]}, centerY={data["centerY"]}')
